---
kind: pipeline
name: default

steps:
  - name: build
    image: node:latest
    commands:
      - yarn
  - name: now
    image: one000mph/drone-now
    environment:
      NOW_TOKEN:
        from_secret: now_token
    settings:
      secret: [now_token]
      deploy_name: personal-website
      prod: true
    when:
      event:
      - promote
      target:
      - production